apiVersion: 1
groups:
    - orgId: 1
      name: 1m Eval Group
      folder: Alert Rules
      interval: 1m
      rules:
        - uid: des6v6lri68sgd
          title: SWAP Used
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 86400
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                adhocFilters: []
                datasource:
                    type: prometheus
                    uid: PBFA97CFB590B2093
                editorMode: code
                exemplar: false
                expr: ((node_memory_SwapTotal_bytes{instance="node-exporter:9100",job="node"} - node_memory_SwapFree_bytes{instance="node-exporter:9100",job="node"}) / (node_memory_SwapTotal_bytes{instance="node-exporter:9100",job="node"})) * 100
                instant: true
                interval: ""
                intervalFactor: 1
                intervalMs: 15000
                maxDataPoints: 43200
                range: false
                refId: A
                step: 240
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 50
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: rYdddlPWk
          panelId: 21
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            __dashboardUid__: rYdddlPWk
            __panelId__: "21"
            description: SWAP > 50%
            summary: SWAP > 50%
          labels: {}
          isPaused: false
          notification_settings:
            receiver: AWS SNS
        - uid: ces6zohrvl3i8e
          title: Utilisation CPU élevée
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)\r\n"
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 85
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            summary: Utilisation CPU Elevée
          isPaused: false
          notification_settings:
            receiver: AWS SNS
        - uid: ces7055gk0ohsf
          title: Site Down
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                disableTextWrap: false
                editorMode: code
                expr: probe_success{instance="https://jordane-brosset.com"}
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: eq
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            summary: Website Down
          isPaused: false
          notification_settings:
            receiver: AWS SNS
