version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    expose:
      - "80"
    networks:
      - web

  reverse-proxy:
    build:
      context: ./nginx
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/jordane-brosset.com:/etc/nginx/conf.d/default.conf
      - ./nginx/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - ./nginx/certs/fullchain.pem:/etc/letsencrypt/live/jordane-brosset.com/fullchain.pem:ro
      - ./nginx/certs/privkey.pem:/etc/letsencrypt/live/jordane-brosset.com/privkey.pem:ro
    networks:
      - web

networks:
  web:
    driver: bridge
