services:
  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-test
    environment:
      - NODE_ENV=test
    ports:
      - "8081:80" # différent de la prod
    volumes:
      - ./default.test.conf:/etc/nginx/conf.d/default.conf:ro

  reverse-proxy:
    image: saas-platform-reverse-proxy
    container_name: reverse-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend-test


networks:
  saas-platform-network:
    driver: bridge
