version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    expose:
      - "80"
    networks:
      - frontend

  reverse-proxy:
    build:
      context: ./nginx
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt/live/jordane-brosset.com/fullchain.pem:/etc/letsencrypt/live/jordane-brosset.com/fullchain.pem:ro
      - /etc/letsencrypt/live/jordane-brosset.com/privkey.pem:/etc/letsencrypt/live/jordane-brosset.com/privkey.pem:ro
      - ./nginx/ssl/options-ssl-nginx.conf:/etc/nginx/ssl/options-ssl-nginx.conf:ro
    networks:
      - frontend
      - web

networks:
  web:
    external: true
  frontend:
    driver: bridge
