apiVersion: 1
contactPoints:
  - name: email
    receivers:
      - uid: email
        type: email
        settings:
          addresses: "jordane.brosset@gmail.com"

policies:
  - orgId: 1
    receiver: email
    group_by: ['alertname']
    routes:
      - matchers:
          - alertname=~".*"
        receiver: email